@PortfolioBackend_HostAddress = http://localhost:5266

GET {{PortfolioBackend_HostAddress}}/api/Floorplan/floorplans
Accept: application/json

### Path finder api call, where user will chose his beginning and end point on a specific image
POST {{PortfolioBackend_HostAddress}}/api/Path/route
Content-Type: application/json

{
  "Start": {
    "XWidth": 807.0, 
    "YHeight": 1289.0
  },
  "End": {
    "XWidth": 3802.0 ,
    "YHeight": 354.0
  },
  "FloorplanName": "game_floor",
  "FloorNumber": 2
}



############ Patients, Doctors, Appointments

GET {{PortfolioBackend_HostAddress}}/api/hospital/patients
Accept: application/json

### POST YOUR ACCESS TOKEN
POST http://localhost:8080/realms/portfolio/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=portfolio_client&username=darren&password=test&grant_type=password&scope=openid

//saving the access token
> {%
    client.global.set("access_token", response.body.access_token);
%}


######### Document creation
POST {{PortfolioBackend_HostAddress}}/api/docugroup/documents
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "Title": "WE BALL"
}

### add some components to the document
POST {{PortfolioBackend_HostAddress}}/api/docugroup/components
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "LastPublishedContentJson": "WE RE HERE 222",
  "ComponentType": 1,
  "GroupDocumentId": "b829d1a1-2a5d-4c78-aa4e-71c01a86db89"
}

### add some paragraph components to the document
POST {{PortfolioBackend_HostAddress}}/api/docugroup/components
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "LastPublishedContentJson": "This is not the end of the world, this is just the end of the chapter",
  "ComponentType": 2,
  "GroupDocumentId": "b829d1a1-2a5d-4c78-aa4e-71c01a86db89"
}

### publish the document
POST {{PortfolioBackend_HostAddress}}/api/docugroup/documents/publish
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "Id": "b829d1a1-2a5d-4c78-aa4e-71c01a86db89"
}

### get the published document
GET {{PortfolioBackend_HostAddress}}/api/docugroup/documents/b829d1a1-2a5d-4c78-aa4e-71c01a86db89
Accept: application/json
Authorization: Bearer {{access_token}}

### get the Draft document
GET {{PortfolioBackend_HostAddress}}/api/docugroup/documents/b829d1a1-2a5d-4c78-aa4e-71c01a86db89/draft
Accept: application/json
Authorization: Bearer {{access_token}}