@PortfolioBackend_HostAddress = http://localhost:5266

GET {{PortfolioBackend_HostAddress}}/api/Floorplan/floorplans
Accept: application/json

### Path finder api call, where user will chose his beginning and end point on a specific image
POST {{PortfolioBackend_HostAddress}}/api/Path/route
Content-Type: application/json

{
  "Start": {
    "XWidth": 807.0, 
    "YHeight": 1289.0
  },
  "End": {
    "XWidth": 3802.0 ,
    "YHeight": 354.0
  },
  "FloorplanName": "game_floor",
  "FloorNumber": 2
}



############ Patients, Doctors, Appointments

GET {{PortfolioBackend_HostAddress}}/api/hospital/patients
Accept: application/json

### POST YOUR ACCESS TOKEN
POST http://localhost:8080/realms/portfolio/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=portfolio_client&username=darren&password=test&grant_type=password&scope=openid

//saving the access token
> {%
    client.global.set("access_token", response.body.access_token);
%}


######### Document creation
POST {{PortfolioBackend_HostAddress}}/api/docugroup/documents
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "Title": "Test document"
}
